apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitops
spec:
  params:
    - name: docker-image
      type: string
    - name: gitops-repo
      type: string
  steps:
    - args:
        - >-
          set -e NEW_IMAGE=$(params.docker-image) 

          echo Setting image to $NEW_IMAGE 

          git clone -b master $(params.gitops-repo) gitops 

          git config --global user.email "tekton@ibmcloud.com" 

          git config --global user.name "Tekton Pipeline" cd gitops/

          mkdir -p prod/matej-ocovsky-pipeline-from-scratch/node-app/

          cp ../source/k8s/manifests.yaml
          prod/matej-ocovsky-pipeline-from-scratch/node-app/ 

          git add .

          git commit -m "Updating image name" --allow-empty 

          git push
      command:
        - /bin/bash
        - "-c"
      image: docker.io/csantanapr/helm-kubectl-curl-git-jq-yq
      name: gitops-step
      resources: {}
      workingDir: $(workspaces.output.path)
  workspaces:
    - name: output
